server:
  port: 10251
spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@
  datasource:
    url: jdbc:mysql://localhost:3306/code-htc?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6390
    password: Xcode-redis?
    database: 1
mybatis-plus:
  configuration:
    call-setters-on-nulls: true
  generator:
    enable: false
    parent: xyz.fusheng
    moduleName: code.htc
mqtt:
  url: "tcp://42.192.222.62:1883"
  username: admin
  password: public
  client-id: code-test-1
